/// Generated by Flutter GetX Starter on 2022-03-25 13:23
import 'package:flutter/material.dart';
import 'package:flutter_base/app/app.dart';
import 'package:flutter_base/app/services/auth_service.dart';

void main() async {
  await initServices();
  runApp(const App());
}

initServices() async {
  await AuthService().init();
}
